name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: npm install --prefer-offline --frozen-lockfile --no-progress --non-interactive
      - name: Format check
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test --coverage
